apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-deployment
  labels:
    app: reviews
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - image: istio/examples-bookinfo-reviews-v3
        name: reviews
        ports:
        - containerPort: 9080
        env:
        - name: RATINGS_HOSTNAME
          value: "10.244.0.40"
        - name: RATINGS_PORT
          value: "9080"