apiVersion: v1
kind: Pod
metadata:
  name: productpage
spec:
  containers:
  - image: istio/examples-bookinfo-productpage-v1
    name: productpage
    ports:
    - containerPort: 9080
    env:
    - name: REVIEWS_HOSTNAME
      value: "10.244.0.37"
    - name: DETAILS_HOSTNAME
      value: "10.244.0.36"
    - name: RATINGS_HOSTNAME
      value: "10.244.0.35"